# SPDX-FileCopyrightText: 2023 Rivos Inc.
#
# SPDX-License-Identifier: Apache-2.0

[package]
name = "rice"
authors = ["Rivos, Inc."]
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = { version = "0.7.6", default-features = false }
const-oid = { version = "0.10.2", features = ["db"] }
der = { version = "0.8.0", features = ["derive", "flagset", "heapless", "oid"] }
digest = { version = "0.11.2", default-features = false }
ed25519 = { version = "2.2.3", default-features = false, features = ["pkcs8"] }
ed25519-dalek = { version = "2.1.1", default-features = false }
flagset = "0.4.6"
hex = { version = "0.4.3", default-features = false }
hkdf = "0.13.0"
hmac = "0.13.0"
sha2 = { version = "0.11.0", default-features = false }
signature = { version = "2.2.0", default-features = false }
spin = { version = "0.10.0", default-features = false, features = ["rwlock"] }
spki = "0.8.0"
zeroize = "1.8.1"
